on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      id: test
      run: |
        set -o pipefail
        echo hello | xargs ./echofail.sh | tee results.txt
        echo "::set-output name=action_fruit::$(cat results.txt)"
    - name: Echo
      if: ${{ always() }}
      run: |
        env
        echo ${{ steps.run_tests.outputs.action_fruit }}
